#!/usr/bin/env bash

# hrsync by Daniele Paroli
# With minor modifications by Tanner Wigington.
#
# Simple script to backup a directory with rsync detecting moved and renamed files.
#
# Use it at your own risk, please see README and LICENSE files.

# ------------------------------------------------------------
# Backup source and target directory.

Source="${1%/}"
Target="${2%/}"
TargetCurrent=$3

# ------------------------------------------------------------
# Name of shadow directory.
Shadow=".rsync_shadow"

# Start doing things.

if [ "${Source:0:1}" != / ]
then
	echo "Source path needs to be an absolute path"
	exit 0
fi

if [ "${Target:0:1}" != / ]
then
	echo "Target path needs to be an absolute path"
	exit 0
fi

if [ -z "$2" ]
then
	echo "Usage:"
	echo "	hrsync source target"
  echo "	hrsync source target yes"
	echo "Example:"
	echo "	hrsync /home/user/Documents /mnt/external/Documents"
  echo "	hrsync /home/user/Documents /mnt/external/Documents yes"
	echo "Please see the README file"
	exit 0
fi

if [ ! -d "$Source/$Shadow" ]
then
	# First time run: create source shadow.
	rsync --archive --delete --progress --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"
fi

# If our target is already up-to-date or partially up-to-date, create a shadow directory there now.
if [ "$3" == "yes" ]
then
   # Update target shadow directory.
	 rsync --archive --delete --progress --link-dest="$Target" --exclude="/$Shadow" "$Target/" "$Target/$Shadow"
fi

# Do real synchronization.
if [ "$3" == "yes" ]
then
    rsync --archive --one-filesystem --xattrs --human-readable --hard-links --verbose --progress --stats --no-inc-recursive --numeric-ids --delete --delete-after "$Source"/ "$Target"
else
    # If our target is already up-to-date or partially up-to-date, just update the remote timestamps.
    # I suspect this will cause issues if the source file is the same size, but has changed content,
    # but I think you could just run a normal sync after to pick up such differences.
    rsync --size-only --times --archive --one-filesystem --xattrs --human-readable --hard-links --verbose --progress --stats --no-inc-recursive --numeric-ids --delete --delete-after "$Source"/ "$Target"
fi

status=$?

if [ $status -eq 0 ]
then
	# Update source shadow directory.
	rsync --archive --delete --progress --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"

	# Update target shadow directory.
	rsync --archive --delete --progress --link-dest="$Target" --exclude="/$Shadow" "$Target/" "$Target/$Shadow"
fi

exit $status
