#!/usr/bin/env bash

# hrsync by Daniele Paroli
# With minor modifications by Tanner Wigington.
#
# Simple script to backup a directory with rsync detecting moved and renamed files.
#
# Use it at your own risk, please see README and LICENSE files.

# ------------------------------------------------------------
# Backup source and target directory.

Source="${1%/}"
Target="${2%/}"

# ------------------------------------------------------------
# Name of shadow directory.
Shadow=".rsync_shadow"

# Start doing things.

if [ "${Source:0:1}" != / ]
then
	echo "Source path needs to be an absolute path"
	exit 0
fi

if [ "${Target:0:1}" != / ]
then
	echo "Target path needs to be an absolute path"
	exit 0
fi

if [ -z "$2" ]
then
	echo "Usage:"
	echo "	hrsync source target"
	echo "Example:"
	echo "	hrsync /home/user/Documents /mnt/external/Documents"
	echo "Please see the README file"
	exit 0
fi

if [ ! -d "$Source/$Shadow" ]
then
	# First time run: create source shadow.
	rsync --archive --delete --progress --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"
fi

# Do real synchronization.
# Adding --size-only --times may helf if it tries to transfer everything.
rsync --archive --one-filesystem --xattrs --human-readable --hard-links --verbose --progress --stats --no-inc-recursive --numeric-ids --delete --delete-after "$Source"/ "$Target"

status=$?

if [ $status -eq 0 ]
then
	# Update source shadow directory.
	rsync --archive --delete --progress --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"

	# Update target shadow directory.
	rsync --archive --delete --progress --link-dest="$Target" --exclude="/$Shadow" "$Target/" "$Target/$Shadow"
fi

exit $status
